### ISSUE TITLE
Static properties in packages

### ISSUE THREAD

**Issue by gaelicmichael** [iroy2000/react-redux-boilerplate#42]
This has served me well as a starter package, so thank you … The problem that I’m having, though, is that if I install a React package that has a class that uses static properties, the compiler chokes (“Unexpected token”). I can use static properties in my own JSX classes, though.

I’m hoping to use the react-hopscotch package but its classes define static propTypes, etc. So I can’t!

I’ve looked into this a bit today but am not by any means a pro when it comes to the complexities of configuration, especially when there are interactions at various levels.

Help on this would be much appreciated!

**Comment by iroy2000** [comment]
I'm glad this starter package have served you well. 

Sorry for getting to you this late, I  hope by the time of this comment, you have that resolved already.

For external React package, since it is /node_modules,  this boilerplate will ignore it and not compile it again. What needs to be done usually is, the external React package will have its own compiled dist/.  You may want to communicate with the author of that external package to make sure they align with the common standards in npm authoring. 

Of course, if you want to, you can whitelist node_modules, so that it can be compiled with this boilerplate, but I usually don't recommend that.
