### ISSUE TITLE
[ Documentation ] Removing hash from url

### ISSUE THREAD

**Issue by natitsolvedsoumenporel** [iroy2000/react-redux-boilerplate#55]
Hi, I want to remove the hash from browser. So I have used BrowserRouter. Here are the changes I have made :- 

src/js/Root.jsx
// import { HashRouter as Router } from 'react-router-dom';
import { BrowserRouter as Router } from 'react-router-dom';

src/js/router.jsx
// import createHistory from 'history/createHashHistory';
import createHistory from 'history/createBrowserHistory';

But it is showing page not found. Could you please help me on this.

**Comment by iroy2000** [comment]
Hi @natitsolvedsoumenporel, 

Hopefully you get that resolved already.  Our team is using html5 history as well ( instead of hash ), it will involve a few more steps than just the above. 

Let me drop that into "Documentation" later, and I will point you to that. 

But if you already figure this out, feel free to contribute to the documentation as well.

Thanks

**Comment by BGrigorovich** [comment]
Hi guys!
So did you figured it out? I ran into the same issue here.

**Comment by BGrigorovich** [comment]
If anyone else struggling with this, you should also set `historyApiFallback` option to `true` in **webpack.config.dev-server.babel.js** under the `webpackConfig.devServer` section.

`webpackConfig.devServer = {
  historyApiFallback: true,
  ...
}
`

Also if you are using express.js or http server like nginx follow the instructions here: https://github.com/ReactTraining/react-router/blob/v2.0.0-rc5/docs/guides/basics/Histories.md#browserhistory

**Comment by iroy2000** [comment]
Closing it since question is resolved.
